// LLModule: top-level .ll file builder

import { LLVMType } from "./types";
import { LLFunction } from "./function";

export class LLModule {
  private declarations: Array<string>;
  private functions: Array<LLFunction>;
  private globals: Array<string>;
  private stringConstants: Array<string>;
  private stringCounter: number;
  private declaredNames: Map<string, boolean>;

  constructor() {
    this.declarations = [];
    this.functions = [];
    this.globals = [];
    this.stringConstants = [];
    this.stringCounter = 0;
    this.declaredNames = new Map();
  }

  // Declare an external function (FFI import)
  declareFunction(name: string, returnType: LLVMType, paramTypes: Array<LLVMType>): void {
    if (this.declaredNames.has(name)) return;
    this.declaredNames.set(name, true);
    const paramStr = paramTypes.join(", ");
    let arr = this.declarations;
    arr.push("declare " + returnType + " @" + name + "(" + paramStr + ")");
    this.declarations = arr;
  }

  isDeclared(name: string): boolean {
    return this.declaredNames.has(name);
  }

  // Define a function
  defineFunction(name: string, returnType: LLVMType, params: Array<[LLVMType, string]>): LLFunction {
    const func = new LLFunction(name, returnType, params);
    let arr = this.functions;
    arr.push(func);
    this.functions = arr;
    return func;
  }

  // Add a global variable
  addGlobal(name: string, ty: LLVMType, init: string): void {
    let arr = this.globals;
    arr.push("@" + name + " = global " + ty + " " + init);
    this.globals = arr;
  }

  // Add an external global variable (declared in another module)
  addExternalGlobal(name: string, ty: LLVMType): void {
    let arr = this.globals;
    arr.push("@" + name + " = external global " + ty);
    this.globals = arr;
  }

  // Add an internal global constant
  addInternalGlobal(name: string, ty: LLVMType, init: string): void {
    let arr = this.globals;
    arr.push("@" + name + " = internal global " + ty + " " + init);
    this.globals = arr;
  }

  // Add a string constant, returns the global name and byte length
  addStringConstant(value: string): [string, number] {
    const name = ".str." + this.stringCounter;
    this.stringCounter = this.stringCounter + 1;

    // Encode string to bytes (UTF-8)
    const bytes = encodeUTF8(value);
    const len = bytes.length;

    // Build LLVM IR constant string (including null terminator for safety)
    const arrayType = "[" + (len + 1) + " x i8]";
    let litStr = "c\"";
    for (let i = 0; i < bytes.length; i = i + 1) {
      const b = bytes[i];
      if (b >= 32 && b < 127 && b !== 34 && b !== 92) {
        litStr = litStr + String.fromCharCode(b);
      } else {
        litStr = litStr + "\\" + hexByte(b);
      }
    }
    litStr = litStr + "\\00\"";

    let scArr = this.stringConstants;
    scArr.push("@" + name + " = private unnamed_addr constant " + arrayType + " " + litStr);
    this.stringConstants = scArr;
    return [name, len];
  }

  // Emit the complete .ll file
  toIR(): string {
    let ir = "; Generated by anvil\n";
    ir = ir + "target triple = \"arm64-apple-macosx15.0.0\"\n\n";

    // String constants
    for (let i = 0; i < this.stringConstants.length; i = i + 1) {
      let sc: string = this.stringConstants[i];
      ir = ir + sc + "\n";
    }
    ir = ir + "\n";

    // Globals
    for (let i = 0; i < this.globals.length; i = i + 1) {
      let gl: string = this.globals[i];
      ir = ir + gl + "\n";
    }
    ir = ir + "\n";

    // External declarations
    for (let i = 0; i < this.declarations.length; i = i + 1) {
      let decl: string = this.declarations[i];
      ir = ir + decl + "\n";
    }
    ir = ir + "\n";

    // Function definitions
    for (let i = 0; i < this.functions.length; i = i + 1) {
      let func: LLFunction = this.functions[i];
      ir = ir + func.toIR() + "\n";
    }

    return ir;
  }
}

function encodeUTF8(s: string): Array<number> {
  const bytes: Array<number> = [];
  for (let i = 0; i < s.length; i = i + 1) {
    const code = s.charCodeAt(i);
    if (code < 0x80) {
      bytes.push(code);
    } else if (code < 0x800) {
      bytes.push(0xC0 | (code >> 6));
      bytes.push(0x80 | (code & 0x3F));
    } else if (code < 0x10000) {
      bytes.push(0xE0 | (code >> 12));
      bytes.push(0x80 | ((code >> 6) & 0x3F));
      bytes.push(0x80 | (code & 0x3F));
    } else {
      bytes.push(0xF0 | (code >> 18));
      bytes.push(0x80 | ((code >> 12) & 0x3F));
      bytes.push(0x80 | ((code >> 6) & 0x3F));
      bytes.push(0x80 | (code & 0x3F));
    }
  }
  return bytes;
}

function hexByte(b: number): string {
  const hex = b.toString(16);
  if (hex.length === 1) {
    return "0" + hex;
  }
  return hex;
}
